CREATE TABLE ZOOPU_ALBUM
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL DEFAULT '',
	cover VARCHAR(100) DEFAULT '',
	description VARCHAR(100) DEFAULT '',
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;

CREATE TABLE ZOOPU_PHOTO
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	albumId BIGINT(20) NOT NULL DEFAULT 0,
	title VARCHAR(100) NOT NULL DEFAULT '',
	text VARCHAR(500) NOT NULL DEFAULT '',
	photoURL VARCHAR(100) NOT NULL DEFAULT '',
	targetURL VARCHAR(100) NOT NULL DEFAULT '',
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;