CREATE TABLE ZOOPU_DEPARTMENT
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	parentId BIGINT(20) NOT NULL DEFAULT 0,
	name VARCHAR(50) NOT NULL DEFAULT '',
	description VARCHAR(100) DEFAULT '',
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;
ALTER TABLE `ZOOPU_DEPARTMENT`  ADD INDEX `parentId` (`parentId`);

CREATE TABLE ZOOPU_FUNCTION
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	parentId BIGINT(20) NOT NULL DEFAULT 0,
	name VARCHAR(50) NOT NULL DEFAULT '',
	description VARCHAR(100) DEFAULT '',
	urls VARCHAR(20480) DEFAULT '',
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;
ALTER TABLE `ZOOPU_FUNCTION`  ADD INDEX `parentId` (`parentId`);

CREATE TABLE ZOOPU_ADMIN
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL DEFAULT '',
	password VARCHAR(100) NOT NULL DEFAULT '',
	name VARCHAR(20) NOT NULL DEFAULT '',
	sex VARCHAR(2) NOT NULL DEFAULT '',
	phone VARCHAR(20) NOT NULL DEFAULT '',
	mobile VARCHAR(20) NOT NULL DEFAULT '',
	email VARCHAR(100) NOT NULL DEFAULT '',
	departmentId BIGINT(20) NOT NULL DEFAULT 0,
	administrator TINYINT(1) NOT NULL DEFAULT 0,
	disable TINYINT(1) NOT NULL DEFAULT 0,
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;

ALTER TABLE `ZOOPU_ADMIN`  ADD UNIQUE INDEX `username` (`username`);
ALTER TABLE `ZOOPU_ADMIN`  ADD INDEX `departmentId` (`departmentId`);

INSERT INTO `ZOOPU_ADMIN` (`id`, `username`, `password`, `name`, `sex`, `phone`, `mobile`, `email`, `administrator`, `disable`, `creatorId`, `createTime`, `updaterId`, `updateTime`) VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 'π‹¿Ì‘±', 'ƒ–', '110', '119', 'shimne@163.com', 1, 0, 1, 0, 0, 0);


CREATE TABLE ZOOPU_ADMIN_FUNCTION
(
	adminId BIGINT(20) NOT NULL DEFAULT 0,
	functionId BIGINT(20) NOT NULL DEFAULT 0
);
ALTER TABLE `ZOOPU_ADMIN_FUNCTION` ADD INDEX `adminId` (`adminId`);
ALTER TABLE `ZOOPU_ADMIN_FUNCTION` ADD INDEX `functionId` (`functionId`);

CREATE TABLE ZOOPU_CUSTOMPAGE
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL DEFAULT '',
	title VARCHAR(100) DEFAULT '',
	keywords VARCHAR(100) DEFAULT '',
	description VARCHAR(100) DEFAULT '',
	content text,
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;