CREATE TABLE ZOOPU_USERBBS
(
	userId BIGINT(20) NOT NULL DEFAULT 0,
	sign VARCHAR(200) NOT NULL DEFAULT '',
	topicNum INT(9) NOT NULL DEFAULT 0,
	replyNum INT(9) NOT NULL DEFAULT 0,
	score BIGINT(20) NOT NULL DEFAULT 0,
	level TINYINT(2) NOT NULL DEFAULT 0
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;
ALTER TABLE `ZOOPU_USERBBS`  ADD UNIQUE INDEX `userId` (`userId`);

CREATE TABLE ZOOPU_BOARD
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	parentId BIGINT(20) NOT NULL DEFAULT 0,
	name VARCHAR(50) NOT NULL DEFAULT '',
	icon VARCHAR(200) NOT NULL DEFAULT '',
	description VARCHAR(200) NOT NULL DEFAULT '',
	topicNum INT(9) NOT NULL DEFAULT 0,
	replyNum INT(9) NOT NULL DEFAULT 0,
	lastTopicId BIGINT(20) NOT NULL DEFAULT 0,
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;
ALTER TABLE `ZOOPU_BOARD`  ADD INDEX `parentId` (`parentId`);

CREATE TABLE ZOOPU_TOPIC
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	boardId BIGINT(20) NOT NULL DEFAULT 0,
	title VARCHAR(200) NOT NULL DEFAULT '',
	context TEXT,
	ipAddr VARCHAR(50) NOT NULL DEFAULT '',
	type TINYINT(1) NOT NULL DEFAULT 0,
	status TINYINT(1) NOT NULL DEFAULT 0,
	viewNum INT(9) NOT NULL DEFAULT 0,
	replayNum INT(9) NOT NULL DEFAULT 0,
	lastReplyerId BIGINT(20) NOT NULL DEFAULT 0,
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;

ALTER TABLE `ZOOPU_TOPIC` ADD INDEX `boardId` (`boardId`);
ALTER TABLE `ZOOPU_TOPIC` ADD INDEX `title` (`title`);

CREATE TABLE ZOOPU_REPLY
(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	topicId BIGINT(20) NOT NULL DEFAULT 0,
	title VARCHAR(200) NOT NULL DEFAULT '',
	context TEXT,
	status TINYINT(1) NOT NULL DEFAULT 0,
	creatorId BIGINT(20) NOT NULL DEFAULT 0,
	createTime BIGINT(20) NOT NULL DEFAULT 0,
	updaterId BIGINT(20) NOT NULL DEFAULT 0,
	updateTime BIGINT(20) NOT NULL DEFAULT 0,
	primary key (id)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=gbk;

ALTER TABLE `ZOOPU_REPLY` ADD INDEX `topicId` (`topicId`);